name: t20_world_cup_result_predictor
description: "T20 World Cup Result Predictor"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  envied: ^0.5.4+1
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  firebase_ui_auth: ^1.14.0
  firebase_ui_oauth_google: ^1.3.2
  flutter_network_connectivity: ^0.0.6
  flutter_riverpod: ^2.4.10
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  google_sign_in: ^6.2.1
  go_router: ^14.0.2
  introduction_screen: ^3.1.14
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.8
  envied_generator: ^0.5.4+1
  flutter_lints: ^3.0.1  
  freezed: ^2.4.7
  json_serializable: ^6.8.0
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.9

flutter:
  uses-material-design: true
